[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["assistant"]

[tool.poe.tasks]
dev = "uv run assistant/main.py"

[project]
name = "deepseek-automizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pynput>=1.8.1",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.3",
    "mypy>=1.20.2",
    "poethepoet>=0.42.1",
]

[tool.basedpyright]
include = ["assistant"]
exclude = ["**/__pycache__"]

typeCheckingMode = "recommended"
reportAny = "none"
reportExplicitAny = "none"
reportIgnoreCommentWithoutRule = false
reportUnannotatedClassAttribute = false
reportMissingSuperCall = false
reportMissingTypeStubs = false
reportUnknownVariableType = false
